[project]
name = "palm-reader"
version = "0.1.0"
description = "AI Palm Reader"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "instructor>=1.10.0",
    "litellm>=1.75.5.post1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.48.0",
]
